AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  HelloWithNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/hello
      Runtime: go1.x
      Events:
        HelloWithName:
          Type: Api
          Properties:
            Path: /hello/{name}
            Method: get
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/hello
      Runtime: go1.x
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            cors: true
  WorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/world
      Runtime: go1.x
      Events:
        World:
          Type: Api
          Properties:
            Path: /world
            Method: get

